# Generated by Django 5.1.4 on 2024-12-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('black_tea', 'Черный чай'), ('white_tea', 'Белый чай'), ('green_tea', 'Зеленый чай'), ('red_tea', 'Красный чай')], max_length=55, unique=True, verbose_name='Наименование чая')),
            ],
            options={
                'verbose_name': 'Чай',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('contact_info', models.CharField(max_length=150, verbose_name='Контактная информация')),
                ('pay_type', models.CharField(choices=[('offline', 'Наличные'), ('online', 'Картой')], max_length=15, verbose_name='Тип оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teahelper.tea', verbose_name='Чай')),
            ],
            options={
                'verbose_name': 'Заказ',
            },
        ),
    ]
