# Generated by Django 5.1.4 on 2024-12-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teahelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='tea',
            options={'verbose_name': 'Чай', 'verbose_name_plural': 'Чаи'},
        ),
        migrations.AlterField(
            model_name='request',
            name='tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teahelper.tea', verbose_name='Чай'),
        ),
    ]
